import type { Metadata } from "next";
import "./globals.css";
import { Footer, Navbar, Sidebar, WhatsappButton } from "@/components";
import { primaryFont, secondaryFont } from "@/config/fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`pt-[209px] md:pt-[286px] xl:pt-[386px] ${primaryFont.variable} ${secondaryFont.variable}`}
      >
        <Navbar />
        <Sidebar />

        <WhatsappButton />
        {children}
        <Footer />
      </body>
    </html>
  );
}
